// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CasinoWebProject.Models
{
    public partial class Transaction
    {
        public int Id { get; set; }
        public string UserId { get; set; } // Change to string to match IdentityUser's key type
        public decimal Amount { get; set; }
        public DateTime Date { get; set; }
        public virtual ApplicationUser User { get; set; } // Change to ApplicationUser
    }
}
